name: 🔒 Security Vulnerability
description: Report a security vulnerability (for non-critical issues only)
title: "[Security]: "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Important Notice
        
        **For critical security vulnerabilities**, please do NOT open a public issue.
        Instead, follow our [Security Policy](https://github.com/sidgaikwad/siddcn/blob/main/.github/SECURITY.md) and report privately.
        
        This template is for **low-severity security concerns** that can be discussed publicly.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: A brief one-line summary of the security concern
      placeholder: e.g., XSS vulnerability in input sanitization
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this vulnerability?
      options:
        - Low (minimal impact, edge case)
        - Medium (limited impact, requires specific conditions)
        - High (significant impact) - Consider private disclosure
        - Critical (severe impact) - DO NOT use this form, report privately
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      description: What type of vulnerability is this?
      options:
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Injection (SQL, Command, etc.)
        - Authentication/Authorization
        - Information Disclosure
        - Denial of Service (DoS)
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the vulnerability
      placeholder: |
        Describe the vulnerability:
        - What is affected?
        - How can it be exploited?
        - What is the potential impact?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this vulnerability?
      placeholder: |
        1. Navigate to...
        2. Enter the following input...
        3. Observe that...
    validations:
      required: true

  - type: textarea
    id: poc
    attributes:
      label: Proof of Concept
      description: Provide code or evidence demonstrating the vulnerability
      placeholder: |
        ```javascript
        // Example exploit code
        ```
    validations:
      required: false

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions on how to fix this?
      placeholder: |
        Possible fixes:
        - Sanitize input using...
        - Add validation for...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have verified this is NOT a critical vulnerability requiring private disclosure
          required: true
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
        - label: I'm willing to help fix this vulnerability
